### PR TITLE
2.5.x ddf 982

### PR DESCRIPTION
**Pull request by jvettraino**
Added the ability to the PEP to continue to attempt to authorize anonymous users and let the PDP process those requests, and determine based on policy if the user should be granted access or not

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-security/21)

### CODE REVIEW

**Comment by jvettraino** [comment]
screwed up the Jira ticket number, so updated that t the correct one of 992

**Comment by stustison** [comment]
This is going to couple anonymous access to the PEP which has nothing to do with anonymous access to the system. The correct way to do this is to utilize the AnonymousInterceptor to create a SAML assertion for an anonymous user. That way anonymous access to the system can be removed if it is not desired.

**Comment by jvettraino** [comment]
@stustison I actually don't see it that way.  I think this is doing exactly what the PEP is supposed to do, and seems to me to be a more logical solution if we talk about true PEPs.  I see a PEP as the Code that enforces the decisions by the PDPs.  The only reason why an anonymous token needs to be gotten is for the PDPs to work properly, is because that is the format that the PDP's expect to make decisions on anonymous access or not.  So this is just ensuring that every request has the proper info to send to the PDP (in this case an anonymous token).

I can add a way to turn on/off anonymous access if you would like.

I feel like the AnonymousInterceptor is not really ideal, and that we shouldn't be generating a fake SAML token and then sending that token through Policy Validation.  It causes extra overhead, and is fragile code (if I change the policy the somewhat hardcoded token being generated isn't going to pass validation) and not intuitive (in my opinion).  I would love to see that phased out for something more PEP based like this. 

I love your suggestion to allow for easily enabling/disabling of anonymous users in the PEP, as it will then allow for that to be configured on a Service Basis,  I added that in this latest commit.

**Comment by stustison** [comment]
I agree with you that the PEP is enforcing the decisions made by the PDP. However, in our architecture we have decoupled anonymous access with the rest of the system not only because it is cleaner, but because it is safer.

In this particular instance, the correct place to put this logic is within the AnonymousInterceptor. The PEP will contact the PDP with whatever token it is provided with, and that token should be a SAML assertion, because that is the way we designed the system. What you are doing here is still acquiring a SAML assertion, you're just getting it via the StsRealm through Shiro as opposed to getting it directly in the AnonymousInterceptor.

I'm also not really sure what you mean by "somewhat hardcoded token". The AnonymousInterceptor reads the policy information available in the WSDL and generates a SAML assertion for an anonymous user based upon that. Failing that, it should fall back to using the STS Client Configuration and use that to generate a SAML assertion just like StsRealm does.

**Comment by menousek** [comment]
@stustison for clarity could you describe where you would like to see the logic?  You stated " The correct way to do this is to utilize the AnonymousInterceptor to create a SAML assertion for an anonymous user. That way anonymous access to the system can be removed if it is not desired." -- so you want it in the Anonymous Interceptor, right?

Assuming that's the case, @jvettraino , can you move it there?

**Comment by stustison** [comment]
@menousek That is right, this logic of using an AnonymousAuthenticationToken should be used within the AnonymousInterceptor as a fallback if no policy is present, or if attempting to read the policy fails for whatever reason. That preserves the separation of concerns that we are currently trying to enforce within the system.

**Comment by beyelerb** [comment]
From the way it was designed, we intend the user object to be created at the onset of the request and the rest of the system just uses the user object. The PDP/PEP just use the user information included in the request. In theory, we could even disable the PDP/PEP and delegate authentication to individual services or applications. As such, it makes more sense to me to separate the generation of the anonymous token from the PEP to fit into the general architecture. We generate the SAML assertion for the anonymous user because that is what we chose as the standard token - it's used in the cookies (to maintain the user's session), in federation, etc.
My vote would be to move it out into it's own interceptor that keeps it separate from the rest of the system. You can still put in the checkbox to enable/disable it - I think that's a good thing.

**Comment by jvettraino** [comment]
I can move it over to the anonymous interceptor especially for the patch branch as I think that makes sense with how the code is designed now.  

However I suggest we looking to improve current design to cut down on complexity, code duplication, etc.  Its hard for someone who isn't intimately familiar with the security code to navigate, as there is a lot of the similar functionality in different places.  There are interceptors, filters, handlers, etc that do similar things (like perform the roll of the PEP, or do message validation), that are in different places b/c of the protocol (SOAP, REST, etc.).  I think the way anonymous requests are handled, should definitely be re-worked, as it is currently much more complex than it should be, and generating SAML doesn't make sense to me (and has HUGE performance implications).  That being said, putting the anon token generation in the PEP (with the code in the current state), is proliferating that confusing logic, so I definitely agree with you guys on moving the code over.

@stustison hardcoded might have been the wrong word, perhaps limited is a better word.  Right now it is parsing the policy to create a Fake Assertion to send through Policy validation.  Getting the Fake token through Policy validation is contingent on parsing the policy in the same manner that the policy is being validated (and all of the pieces) - when in reality the goal is for the Fake token to always pass validation.

**Comment by shaundmorris** [comment]
So @jvettraino were you still planning on moving it over to the anonymous interceptor? I believe it worth starting a separate thread on evaluating the design since I'm sure there is still good discussion that needs to take place there.

**Comment by jvettraino** [comment]
@shaundmorris , yup I will get this PR updated (or create a new one) with that logic this evening or tomorrow.

**Comment by jvettraino** [comment]
@shaundmorris just an FYI - I talked with @beyelerb and he is doing some work in this area, so he is going to let me know what he wants me to do here (he might just do it himself).

**Comment by shaundmorris** [comment]
@jvettraino thanks for the update!

**Comment by jvettraino** [comment]
Closing this one out, as the preferred solution was implemented as part of DDF-1019

**Pull request closed without merging**
