### PR TITLE
DDF-1020 the anonymous interceptor wrapper is no longer needed since the...

### PR DESCRIPTION
**Pull request by jvettraino**
... functionality can/should be enabled/disabled via the metatype property in the main anonymous interceptor

Since this is removing something, I decided it was probably best to do it in the master, but if you think it can go into the bug fix branch feel free to apply it to that branch as well.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-security/23)

### CODE REVIEW

**Comment by stustison** [comment]
This doesn't seem quite right to me. The AnonymousInterceptor is meant to be pulled in as an OSGi service. If soap endpoints add the interceptor directly, then you cannot add or remove the anonymous feature and you create coupling between your endpoint and the anonymous stuff.

**Comment by jvettraino** [comment]
@stustison  - @beyelerb added the ability to turn off the Anon handling through the Admin Settings (https://github.com/codice/ddf-security/blob/master/interceptor/security-interceptor-anonymous/src/main/java/org/codice/ddf/security/interceptor/AnonymousInterceptor.java#L128) which as I understand it is the preferred way to enable/disable functionalty since it doesn't impact the Admin App status (like turning off a required feature does right now).

Also, from what I can tell, the anon wrapper isn't reliable if you have other PhaseIntercpetors available as OSGi services

**Comment by jvettraino** [comment]
Should I remove the exporting of the AnonInterceptor as an OSGi Service as part of this?

**Comment by stustison** [comment]
Yeah I guess you could. There is no reason to export it if it isn't working quite right. No one had mentioned that to me. Is there a ticket that referred to the OSGi service approach not working correctly?

**Comment by jvettraino** [comment]
Let me try to clarify.  So currently the AnonInterceptor gets exported as a PhaseInterceptor to the OSGi Registry.  The AnonInterceptorWrapper just pulls the first service it finds for PhaseInterceptor (which may or may not be the anonInterceptor, depending on what else is exported - so this is where it is not reliable).  So it works correctly, it is just fragile and could lead to very unexpected behaviors if other Services are exported.

Additionally there were updates made to be able to toggle the anon functionality on/off via configs instead of features (which was original purpose of the AnonWrapper as you mentioned - except to allow it to be done as a feature instead).

So without the anonWrapper, the AnonInterceptor would always be installed, and you could control the functionality through the Admin Configuration.

Does that make more sense?

**Comment by stustison** [comment]
That makes sense, but now you won't be able to remove anonymous access to the REST services. If we are going to go the route of relying on a config admin setting, then we need to update the AnonymousHandler on the REST side as well.

**Comment by jvettraino** [comment]
On the REST Side I thought that was already taken care of in the Security Context Policy settings where you specify the URl and the type of handler/auth that is supported?

Or am I missing something?  If so, then yes we should create a ticket.  

From my understanding the goal is to move away from using Features to turn on/off capabilities and do it through explicit configuration options.

**Comment by stustison** [comment]
Yeah, I suppose that is true that you could turn it off that way. I guess I was talking more about wanting to disable it globally.

**Comment by shaundmorris** [comment]
@jvettraino, @stustison  what did we decide on this PR? We haven't had any activity on it 21 days...

**Comment by jvettraino** [comment]
I think it depends on what direction you want to go.  

So currently some apps might be leveraging the AnonInterceptorWrapper since it was released in security 2.5.x.  So this would be a "breaking" change for them if it is removed (and they would have to be updated to find the AnonInterceptor directly (or create it).  If we go the find route we probably need to update this to include a specific property (or create an interface) that is exported since it is exported as a PhaseInterceptor (and as someone wanting to pull in the AnonInterceptor they would specifically want it, instead of any PhaseInterceptor).  Or alternatively, we don't have to export it at all and just have SOAP Services instantiate it directly (this would remove the "global" configuration option and require it to be a per-service option).

Also you might double check that everyone is on board with going the Configuration Route (explicit config settings) vs feature route for things like this (which I think makes a lot of sense because you have much more flexibility).

If breaking changes aren't allowed for a 2.6.0 security, then I would suggest moving this to 3.0 (or just closing out this PR, as there may be other things that change for 3.0 that make this OBE).

**Comment by stustison** [comment]
Closing out this pull request as it is a breaking change. We can look at this for the 3.0 release if it is not covered in some other way.

**Pull request closed without merging**
