### PR TITLE
DDF-984 Fix CAS authentication and unit tests.

### PR DESCRIPTION
**Pull request by brendan-hofmann**

### CODE REVIEW

**Comment by mrmateo** [comment]
@brendan-hofmann can you give a brief summary what the issue was and how you fixed it? It's a little hard to see from the changes as there were some lines changed due to formatting.

**Comment by brendan-hofmann** [comment]
The salient changes are as follows:
 - the proxy filter got moved up so that it is always checked first. this ensures that all the redirects are handled properly and eliminates an NPE from the session not being created when the CAS handler is first called, since the proxy filter/cas library take care of creating the session for us.
 - the cache was eliminated. it's unnecessary, as the CAS token is already available in the HTTP session and jetty takes care of giving us the right session once it has been created.
 - we don't need to check for cookies at all, according to @stustison , so that logic and corresponding unit test were removed.
 - the unit tests were updated to always provide the mock proxy filter, since we always call it now, and to replace the cache test logic with corresponding logic using a persistent session instead.

**Comment by mrmateo** [comment]
Thanks for the summary. I believe the caching was added there as a fail-safe as there were some edge cases where the sessions would not be propagated fully and it would need to fall back to the caching/cookies. 

What kind of use-case testing did you perform after making these changes? I believe one of the cases was using the Search UI in a browser that was not storing cookies (either through security settings (or a private mode) or using a non-conformant hostname for secure cookies).

**Comment by brendan-hofmann** [comment]
I did do a lot of testing in private browsing mode. I can't speak to non-conformant hostnames. @stustison might want to weigh in on that, since he's the one who suggested removing the caching logic.

If you could point me to what the edge cases are and how to reproduce them, I could certainly do more verification to see if we still need the cache or not.

**Comment by mrmateo** [comment]
The only one I could think of is the one I mentioned, hitting the search ui in a private mode :)

If that worked for you (i.e. you could perform searches and see thumbnails on results..etc), and you only needed to log into CAS once, then this should be good to go.

**Comment by stustison** [comment]
@mrmateo I fixed a few issues regarding sessions in the last few weeks that were requiring us to use the caching logic in the first place. It should all be working correctly with @brendan-hofmann's change now that those issues are fixed.

**Comment by mrmateo** [comment]
OK, that was the step I was missing. Thanks @stustison !

**Comment by brendan-hofmann** [comment]
@shaundmorris I'm using the codice formatter, so I'd assume the latter...

**Comment by mrmateo** [comment]
@brendan-hofmann @shaundmorris - I noticed that as well. I haven't looked deeply, but I am thinking it might not be a setting that eclipse exports in the file. Looks like by default eclipse always wraps class and method annontations while intellij does not.

**Comment by brendan-hofmann** [comment]
@mrmateo I don't recall this always being an issue, so I suspect the IntelliJ default  might have changed at some point. I don't feel strongly about either form, but I can fix it if you like.

**Comment by mrmateo** [comment]
I'm fine either way. @shaundmorris was the one who mentioned it :) Either way, I will merge this in tomorrow (Jan 9) if there are no other comments.

**Comment by brendan-hofmann** [comment]
I just checked again, and the IntelliJ default is to wrap always. You only get them unwrapped if you apply the Codice formatter profile, which I have done.

I do care about stylistic consistency, but these results are confusing. :/

**Comment by mrmateo** [comment]
Hmm, that's interesting. Can you make that quick change then and I'll merge this? We (either you, @shaundmorris , or myself) can create a ticket for the formatter xml and maybe to add it to the checkstyle.

**Comment by brendan-hofmann** [comment]
@mrmateo I fixed the formatting and created DDF-1003 for the formatter issue.

**Comment by mrmateo** [comment]
Thanks! Updates look good. Merging in...

**Pull request merged**
